### ISSUE TITLE
bilbil.py运行后超时

### ISSUE THREAD

**Issue by 1826013782** [MgArcher/Text_select_captcha#17]
Traceback (most recent call last):
  File "C:/Users/86157/Desktop/Text_select_captcha-master/bilbil.py", line 120, in <module>
    jd.bibi()
  File "C:/Users/86157/Desktop/Text_select_captcha-master/bilbil.py", line 88, in bibi
    (By.XPATH, xpath)))
  File "C:\Anaconda3\envs\Text_select_captcha-master\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by MgArcher** [comment]
使用新版代码解决此问题

**Comment by 1826013782** [comment]
收到，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MgArcher/Text_select_captcha"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MgArcher/Text_select_captcha] bilbil.py运行后超时 (#17)





 
使用新版代码解决此问题
