### ISSUE TITLE
 Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation'

### ISSUE THREAD

**Issue by 1826013782** [MgArcher/Text_select_captcha#20]
Traceback (most recent call last):
  File "C:/Users/86157/Desktop/Text_select_captcha-master1/bilbil.py", line 27, in <module>
    cap = captcha.TextSelectCaptcha()
  File "C:\Users\86157\Desktop\Text_select_captcha-master1\src\captcha.py", line 29, in __init__
    self.yolo = YOLO(path(save_path, yolo_path), GPU)
  File "C:\Users\86157\Desktop\Text_select_captcha-master1\src\utils\orientation.py", line 243, in __init__
    self.model = attempt_load(weights, map_location=self.device)
  File "C:\Users\86157\Desktop\Text_select_captcha-master1\src\utils\models\experimental.py", line 117, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "C:\Anaconda3\envs\Text_select_captcha-master\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Anaconda3\envs\Text_select_captcha-master\lib\site-packages\torch\serialization.py", line 852, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from 'C:\\Anaconda3\\envs\\Text_select_captcha-master\\lib\\site-packages\\torch\\nn\\modules\\activation.py'>

**Comment by MgArcher** [comment]
请使用最新版代码，新版代码已解决此问题
