### ISSUE TITLE
models一直报错，请问什么原因呀

### ISSUE THREAD

**Issue by lynnout** [MgArcher/Text_select_captcha#3]
Traceback (most recent call last):
  File "D:/我的工作/AirtestScripts2020/图像识别/Text_select_captcha-master/mode_one.py", line 10, in <module>
    from src import orientation
  File "D:\我的工作\AirtestScripts2020\图像识别\Text_select_captcha-master\src\orientation.py", line 28, in <module>
    from src.utils.models import *
  File "D:\我的工作\AirtestScripts2020\图像识别\Text_select_captcha-master\src\utils\models.py", line 125
    f"conv_{module_i}",
                     ^
SyntaxError: invalid syntax

看了一下格式觉得并没有问题啊！

**Comment by lynnout** [comment]
![image](https://user-images.githubusercontent.com/50066822/93181388-fe1b0880-f76a-11ea-8f03-84279aafa097.png)
报错的是这个位置

**Comment by 15950552800** [comment]
查看一下你的python版本，这个语法糖是python3.6以上的版本才能用

**Comment by lynnout** [comment]
果然啊，我是3.5，那我改写一下所有的f拼接好啦，感谢作者！

**Comment by 15950552800** [comment]
不客气
